config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    get '/admins' => 'homes#top'
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update]
  	#resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	#resources :genres,only: [:index,:create,:edit,:update, :show]
  	#resources :orders,only: [:index,:show,:update] do
  	 # member do
    #    get :current_index
     #   resource :order_details,only: [:update]
    #  end
     # collection do
      #  get :today_order_index
      #end
  #  end
  end


# 顧客用
devise_scope :customer do
    post '/customers/show' => 'public/customers#show'
  end
  
 scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :customers,     only: [:show,:create, :edit, :update, :destroy] do
      collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end  
    resources :articles,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources  :likes,     only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
    end
    get 'articles/:id' => 'articles#index'
    get '/customer/unsubscribe' => 'customer#unsubscribe'
    get '/search' => 'searches#search'
  end

  namespace :admin do
    resources :customers,     only: [:index, :show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :edit, :update, :destroy]
    get '/search' => 'searches#search'
  end
  
  get 'maps/index'
  resources :maps, only: [:index]

post "likes/:article_id/create", to: "likes#create", constraints: {article_id: /\d+/}, as: :likes_create
post "likes/:article_id/delete", to: "likes#delete", constraints: {article_id: /\d+/}, as: :likes_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :customer
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  #has_many :article, dependent: :destroy
  has_one :spot
  #accepts_attachments_for :article_images, attachment: :image, append: true

  validates :customer_id, presence: true
  validates :title  , presence: true, length: {maximum: 200}
  validates :body, presence: true, length: {maximum: 200}
  # 存在性のバリデーション
  validates :lat, presence: true
  validates :lng, presence: true
  validates :address, presence: true, length: {maximum: 200} 
 
  # バリデーションの前に送信されたaddressの値によってジオコーディング(緯度経度の算出)を行う
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
  #geocoded_by :address
  #after_validation :geocode, if: :address_changed?


  #def liked_by(customer, article)
   # Like.where(customer_id: customer.id, article_id: article.id).exists?
  #end
  def liked?(customer)
   likes.where(customer_id: customer.id).exists?
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
   
  
  def index
    @articles = Article.includes(:customer).order("created_at DESC")
    @article = Article.all.page(params[:page]).per(10)
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: "削除しました"
  end
  
   private
 #def if_not_admin
  #  redirect_to root_path unless current_customer.admin?
  #end

  def article_params
    params.require(:article).permit(:title, :body, :address, :lat, :lng, :id)
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/index.html.erb
 <div class="container">
<h3 class="my-5">投稿一覧表示</h3>

<!--<div>
  <% if customer_signed_in? %>
    <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %>
    <%= "#{current_customer.first_name}さんはログイン中です"%>
  <% else %>
    <%= link_to 'ユーザー新規登録', new_customer_registration_path %>
    <%= link_to 'ログイン', new_customer_session_path %>
  <% end %>
</div>

<div>
  <% if customer_signed_in? && current_customer.admin? %>
    <%= link_to '管理者用:投稿ページ', new_admin_article_path %>
  <% end %>
</div>
-->

  
    <div class="dai">
    <% @articles.each do |article| %>
       
        <tr>タイトル : </tr>
        <div class="sabudai">
        <td><%= article.title %></td>
        </div>
      
        <tr>内容 : </tr>
        <div class="sabudai">
        
        <td><%= article.body %></td>
        </div>
      
        <tr>投稿場所 : </tr>
          <div class="sabudai">
        
        <td><%= article.address %></td>
        </div>
          </br>
    <% end %>
</div>