config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    get '/admins' => 'homes#top'
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update]
  	#resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	#resources :genres,only: [:index,:create,:edit,:update, :show]
  	#resources :orders,only: [:index,:show,:update] do
  	 # member do
    #    get :current_index
     #   resource :order_details,only: [:update]
    #  end
     # collection do
      #  get :today_order_index
      #end
  #  end
  end


# 顧客用
devise_scope :customer do
    post '/customers/show' => 'public/customers#show'
  end
  
 scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :customers,     only: [:show,:create, :edit, :update, :destroy] do
      collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end  
    resources :articles,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources  :likes,     only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
    end
    get 'articles/:id' => 'articles#index'
    get '/customer/unsubscribe' => 'customer#unsubscribe'
    get '/search' => 'searches#search'
  end

  namespace :admin do
    resources :customers,     only: [:index, :show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :edit, :update, :destroy]
    get '/search' => 'searches#search'
  end
  
  get 'maps/index'
  resources :maps, only: [:index]

post "likes/:article_id/create", to: "likes#create", constraints: {article_id: /\d+/}, as: :likes_create
post "likes/:article_id/delete", to: "likes#delete", constraints: {article_id: /\d+/}, as: :likes_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  #has_many :addresses, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, uniqueness: true
  #validates :comment_text, presence: true, length: { maximum: 1000 }

  def self.search_for(content,method)
    return none if content.blank?
     if method == 'forward'
      # カラムが2つの部分を1つに補う
       f_customer = Customer.where('first_name LIKE ?',content + '%')
       l_customer = Customer.where('last_name LIKE ?',content + '%')
       customers = f_customer + l_customer
     elsif method == 'backword'
       Customer.where('first_name LIKE ?', '%' + content)
       f_customer = Customer.where('first_name LIKE ?', '%' + content)
       l_customer = Customer.where('last_name LIKE ?', '%' + content)
       
       customers = f_customer + l_customer
     else
       f_customer = Customer.where('first_name LIKE ?', '%' + content + '%')
       l_customer = Customer.where('last_name LIKE ?', '%' + content + '%')
       
       customers = f_customer + l_customer
     end
  end
  
  
         
         
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all.page(params[:page]).per(10)
    
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました。"
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end
   
  private
   def customer_params
     params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:phone_number,:email,:is_deleted)
   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class="table">
      <thead>
        <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
        </tr>
      </thead>
        
      <tbody>
        <% @customers.each do |customer| %>
         <tr>
             <td class="info col-xs-1">
                <%= customer.id %>
             </td>
             <td class="text-left">
               <%= link_to admin_customer_path(customer) do %><%= customer.last_name %><%= customer.first_name %><% end %>
             </td>
             <td class="text-left">
                <%= customer.email %>
             </td>
             <td class="col-xs-2">
                <% if customer.is_deleted == true%>
                  <p class="text-secondary">退会済</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
             </td>
         </tr>
        <% end %>
      </tbody>
    </table>

app/views/admin/customers/edit.html.erb
<% provide(:title, "会員情報編集") %>
<div class="container">
  <h2 class="text-center m-5"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h2>
  <div class="row d-flex justify-content-center">
    
  <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
    <div class="col-xs-10 offset-1">
      <div class="form-group col-xs-9">
        <%= f.label :"会員ID", class: "col-sm-4" %>
        <%= f.label :"#{@customer.id}" %>
      </div>
      <div class="form-group col-xs-9">
        <%= f.label :"氏名", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name, class: "col-sm-3 form-control-static" %>　
        <%= f.text_field :first_name, class: "col-sm-3 form-control-static name" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"フリガナ", class: "col-sm-4 control-label" %>
        <%= f.text_field :last_name_kana, class: "col-sm-3 form-control-static name" %>
        <%= f.text_field :first_name_kana, class: "col-sm-3 form-control-static name" %>
      </div>
      
      <div class="form-group col-xs-9">
        <%= f.label :"メールアドレス", class: "col-sm-4 control-label" %>
        <%= f.text_field :email, class: "col-sm-6" %>
      </div>

      <div class="form-group col-xs-9">
        <%= f.label :"会員ステータス", class: "col-sm-4 control-label" %>
        　<%= f.radio_button :is_deleted, false %>
        　<%= f.label :is_deleted, "有効"%>
        　<%= f.radio_button :is_deleted, true %>
        　<%= f.label :is_deleted, "退会" %>
      </div>
    </div>
      <div class="form-group col-xs-9 d-flex justify-content-around">
        <%= f.submit '変更を保存する' ,class: "btn btn-success" %>
        <%= link_to '会員詳細画面へ戻る',admin_customer_path, class:"btn btn-outline-secondary"%>
      </div>

  <% end %>
    
  </div>
</div>

app/views/admin/customers/index.html.erb
<% provide(:title, "会員情報一覧") %>
<div class="container">
 <h2 class="my-5">会員一覧</h2>
  <div class="row d-flex justify-content-center">
  <%= render 'index', customers: @customers%>
 </div>
 <div class="d-flex justify-content-center"><%= paginate(@customers)%></div>
</div>

app/views/admin/customers/show.html.erb
<% provide(:title, "会員情報詳細") %>
<div class="container">
  <h2 class="mt-5 text-center"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
    <div class="row m-5">
      <div class="col-10 offset-1">
          <table class="table">
            <tr>
              <th class="text-center">会員ID</th>
              <td><%= @customer.id%></td>
            </tr>
            <tr>
              <th class="text-center">氏名</th>
              <td><%= @customer.last_name %><%= @customer.first_name %></td>
            </tr>
            <tr>
              <th class="text-center">フリガナ</th>
              <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
            </tr>
            <tr>
              <th class="text-center">メールアドレス</th>
              <td><%= @customer.email%></td>
            </tr>
            <tr>
              <th class="text-center">会員ステータス</th>
              <% if @customer.is_deleted == true%>
               <td class="text-secondary">退会済み</td>
              <% else %>
               <td class="text-success">有効</td>
              <% end %>
            </tr>            
          </table>
          <div class="d-flex justify-content-around">
            <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success"%></p>
            <p><%= link_to "会員一覧",admin_customers_path, class:"btn btn-primary"%></p>
          </div>
   　　 </div>
  　</div>
 </div>