config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  
# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
    get '/admins' => 'homes#top'
  	get '/search'=>'search#search'
    resources :customers,only: [:index,:show,:edit,:update]
  	#resources :items,only: [:index,:new,:create,:show,:edit,:update,]
  	#resources :genres,only: [:index,:create,:edit,:update, :show]
  	#resources :orders,only: [:index,:show,:update] do
  	 # member do
    #    get :current_index
     #   resource :order_details,only: [:update]
    #  end
     # collection do
      #  get :today_order_index
      #end
  #  end
  end


# 顧客用
devise_scope :customer do
    post '/customers/show' => 'public/customers#show'
  end
  
 scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :customers,     only: [:show,:create, :edit, :update, :destroy] do
      collection do
  	     get 'quit'
  	     patch 'out'
  	  end
  	end  
    resources :articles,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resources  :likes,     only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
    end
    get 'articles/:id' => 'articles#index'
    get '/customer/unsubscribe' => 'customer#unsubscribe'
    get '/search' => 'searches#search'
  end

  namespace :admin do
    resources :customers,     only: [:index, :show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :edit, :update, :destroy]
    get '/search' => 'searches#search'
  end
  
  get 'maps/index'
  resources :maps, only: [:index]

post "likes/:article_id/create", to: "likes#create", constraints: {article_id: /\d+/}, as: :likes_create
post "likes/:article_id/delete", to: "likes#delete", constraints: {article_id: /\d+/}, as: :likes_delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_error_message.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% flash.each do |key, value| %>
    <%#= content_tag(:div, value, class: key) %>
    <div class="<%= key %> w-75 mx-auto">
      <%= value %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white pt-1 pb-1">
        <div class="container">
          <h6 class="text-light text-right py-1 mb-0">Copyright © 2022 Y.S</h6>
        </div>
</footer>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
      <% if admin_signed_in? %>
        <%= link_to "bIkE room 管理者", root_path, class:"header-title navbar-brand"%>
      <% else %>
        <%= link_to "bIkE room", root_path, class:"header-title navbar-brand"%>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if customer_signed_in?  %>
          <div class="nav-item mt-2 ml-5">
                ようこそ <%= current_customer.last_name %> さん
          </div>
        <% end  %>
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item"><%= link_to "マイページ", customer_path(current_customer.id), class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "投稿", new_article_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "投稿一覧", articles_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
          <% elsif current_admin %>
            <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "投稿一覧", admin_articles_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
          <% else %>
            <li class="nav-item"><%= link_to "概要", about_path,class: 'btn btn-outline-secondary mx-3 my-1' %></li>
            <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "会員ログイン", new_customer_session_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
            <li class="nav-item"><%= link_to "管理者用", new_admin_session_path, class: 'btn btn-outline-secondary mx-3 my-1'  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bIkE room</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
   </head>

  <body>
    <div class="footer-fixed">
      <%= render "layouts/header" %>
      <%= render "layouts/errors" %>
      <%= render 'public/searches/form' %>
      
    <%= yield %>
    </br>
    </br>
    </br>
      <%= render "layouts/footer" %>
    </div>
  </body>
  <%= debug params if Rails.env.development? %>
  <%= @customer.inspect if Rails.env.development? %>
  
</html>